services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false


  #  mongo-express:
#    image: mongo-express
#    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
#    ports:
#      - 8080:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#      - ME_CONFIG_MONGODB_SERVER=mongodb

  om-api:
    build:
      context: .
    container_name: om-api
    hostname: om-api
    ports:
      - 4111:4111
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=om_transactions
    volumes:
      - ./config/application.properties:/app/config/application.properties
#    networks:
#      - deals_payment_net

volumes:
  mongo-data:

networks:
  deals_payment_net:
    external: true
