services:
  om-api:
    build:
      context: .
    container_name: om-api
    hostname: om-api
    image: om-api
    ports:
      - "4111:4111"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example2@mongo:27017/om_transactions?authSource=admin
    volumes:
      - payment_config:/app/config/application.properties
    networks:
      - networkName

volumes:
  payment_config:
    name: payment_config

networks:
  networkName:
    external: true
